import React from 'react'

export const ProjectionsScreen = () => {
  return (
    <div >
      proyecciones  navbar
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam ipsam reprehenderit ex inventore perspiciatis nisi dolore! Optio cumque dolores, est quaerat et ratione laboriosam saepe delectus, doloremque ut cum laborum.</p>
    </div>
  )
}
